<a href="https://colab.research.google.com/github/AscendPriyansh/HandsOnMachineLearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ARRAY | ARRAY CREATION

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.linspace(1, 5, 8)
arr

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [ ]:
arr = np.random.rand()
arr

0.7520349450779307

In [ ]:
arr = np.random.rand(5)
arr

array([0.05689088, 0.51310505, 0.1918931 , 0.57508099, 0.42759466])

In [ ]:
arr = np.random.randn()
arr

-1.8329337316177874

In [ ]:
arr = np.random.randint(10, 15, 10)
arr

array([10, 12, 14, 10, 11, 13, 10, 14, 12, 11])

In [ ]:
arr = np.array([[1,2],[3,4]])
arr.shape

(2, 2)

### ARRAY | ARRAY METHODS

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

np.int64(1)

In [ ]:
print(arr.min())

1


In [ ]:
print(arr.max())

9


In [ ]:
print(arr.mean())

5.0


In [ ]:
#Give the index of the maximum element in the array
print(arr.argmax())

8


In [ ]:
#Give the index of the minimum element in the array
print(arr.argmin())

0


In [ ]:
print(arr.sum())

45


In [ ]:
print(arr.std())

2.581988897471611


In [ ]:
#Sum of rows
print(arr.sum(axis=1))

[ 6 15 24]


In [ ]:
#Sum of columns
print(arr.sum(axis=0))

[12 15 18]


### ARRAY | ARRAY RESHAPE & RESIZING

In [ ]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### ARRAY | ARRAY INDEXING & SLICING OF VECTORS

In [ ]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
print(arr[1])

12


In [ ]:
arrSlice = arr[2::2]
arrSlice

array([13, 15, 17, 19])

### ARRAY | INDEXING & SLICING OF MATRIX

In [ ]:
arr = np.arange(1, 81).reshape(10, 8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
arr[3:7, 3:6]

array([[28, 29, 30],
       [36, 37, 38],
       [44, 45, 46],
       [52, 53, 54]])

### ARRAY | ARRAY BOOLEAN INDEXING

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]

### ARRAY | ARRAY OPERATIONS

In [ ]:
arr1 = np.array([1,2,3,4,0])
arr2 = np.array([6,7,8,9,5])

In [ ]:
arr1 + arr2

array([ 7,  9, 11, 13,  5])

In [ ]:
arr1 * arr2

array([ 6, 14, 24, 36,  0])

In [ ]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [ ]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.        ])

In [ ]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [ ]:
arr1 ** arr2

array([     1,    128,   6561, 262144,      0])

In [ ]:
arr1 % arr2

array([1, 2, 3, 4, 0])

In [ ]:
#BOARDCASTING
#Numpy helps to apply mathematical operations by streching the smaller array to bigger one

In [ ]:
arr = [1,2,3,4,5]

arr = np.array(arr)

arr*11

array([11, 22, 33, 44, 55])

### ARRAY | ARRAY MATRIX OPERATIONS

In [ ]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
#Matrix Multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [ ]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
#Transpose
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
B.T

array([[5, 7],
       [6, 8]])

### ARRAY | ADVANCED ARRAY MANIPULATION

In [ ]:
#Stacking Array
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [ ]:
np.stack((A, B))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vsplit(A, 2)

[array([[1, 2]]), array([[3, 4]])]

In [ ]:
np.hsplit(A, 2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [ ]:
np.column_stack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.row_stack((A,B))

/tmp/ipykernel_1242/2616905860.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((A,B))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### NUMPY | EXERCISE

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
for row in s :
    if row.sum()!=45 :
      print("Invalid")
      break
else :
    print("Valid")

for col in s :
  if col.sum()!=45 :
    print("Invaid")
    break
else :
  print("Valid")

for i in range(0, 27, 3) :
  for j in range(0, 9, 3) :
    if s[i:i+3, j:j+3].sum()!=45 :
      print("Invalid")
      break
else :
  print("Valid")

Valid
Valid
Invalid
Invalid
Invalid
Invalid
Invalid
Invalid
Valid


In [ ]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#Find the average age of students.
data[:,:1].mean()

np.float64(18.4)

In [ ]:
#Extract Math marks of all students.
data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [ ]:
#Find the highest Science mark.
data[:,2:].max()

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
bool_index = data[:,1]>90
data[bool_index]

array([[19, 92, 88]])

In [ ]:
#Increase Math marks of all students by 5.
data[:, 1]+5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.
bool_index = data[:,0]<19
arr = data[bool_index]
len(arr[:,0])

3

In [ ]:
#Calculate the average marks in each subject (column-wise mean)
data[:, 1:].mean(axis=0)

array([81.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.
bool_index = data[:, 1]>=80
data[(data[:, 1]>=80)] & data[(data[:, 2]>=80)]

array([[18, 84, 72],
       [17, 76, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[:, 2][data[:, 2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])